-- Generated by clipboard.sh: yank to the host clipboard via OSC 52 (nvim 0.10+)
local ok, osc52 = pcall(require, "vim.ui.clipboard.osc52")
if not ok then return end
-- Terminals don't allow reading the clipboard via OSC 52, so `p` pastes the
-- last yank; paste from Windows/macOS apps with Ctrl+V / Cmd+V.
local function paste()
  return { vim.fn.split(vim.fn.getreg(""), "\n"), vim.fn.getregtype("") }
end
vim.g.clipboard = {
  name = "OSC 52",
  copy  = { ["+"] = osc52.copy("+"), ["*"] = osc52.copy("*") },
  paste = { ["+"] = paste, ["*"] = paste },
}
vim.opt.clipboard = "unnamedplus"
vim.keymap.set("v", "<C-c>", '"+y', { desc = "Copy to host clipboard" })
-- Ctrl+V is taken by the terminal for pasting: use Ctrl+Q for visual block.
